spring.application.name=npdstreaming

omdb.api.key=${OMDB_API_KEY}
chatGPT.api.key=${API_KEY_CHATGPT}

spring.datasource.url=${DB_URL}
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.format-sql=true

hibernate.dialect=org.hibernate.dialect.HSQLDialect
